## Tensorの基礎

In [1]:
# 環境を自分で用意する場合は以下のコマンドでpytorchをインストール
# pip install torch

In [2]:
import torch
import numpy as np
# 乱数の種を固定
torch.manual_seed(42)

### Tensorの作成

In [3]:
my_list = [1, 2, 3, 4]
tensor_from_list = torch.tensor(my_list)
print("Tensor from list:", tensor_from_list)

Tensor from list: tensor([1, 2, 3, 4])


In [4]:
type(tensor_from_list)

torch.Tensor

In [5]:
# intのリストで作成したTensorのデータ形はint64
tensor_from_list.dtype

torch.int64

In [6]:
# floatのlistで作ったtensorはfloat32
my_list = [1., 2., 3., 4.]
tensor_from_list = torch.tensor(my_list)
print("Tensor from list:", tensor_from_list)
tensor_from_list.dtype

Tensor from list: tensor([1., 2., 3., 4.])


torch.float32

In [7]:
# dtype引数でデータ型を指定
tensor_from_list = torch.tensor(my_list, dtype=torch.float64)
tensor_from_list

tensor([1., 2., 3., 4.], dtype=torch.float64)

### Tensor作成

In [8]:
zeros_tensor = torch.zeros((2, 3))
ones_tensor = torch.ones((2, 3))
eye_tensor = torch.eye(3)
random_tensor = torch.rand((2, 3))

In [9]:
print(zeros_tensor, zeros_tensor.dtype)
print(ones_tensor, ones_tensor.dtype)
print(eye_tensor, eye_tensor.dtype)
print(random_tensor, random_tensor.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.float32
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]) torch.float32
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]]) torch.float32


In [10]:
# NumPyとの対応
np_zeros = np.zeros((2, 3))
np_ones = np.ones((2, 3))
np_eye = np.eye(3)
np_random = np.random.rand(2, 3)
# Numpy Arrayのデフォルトはfloat64であることに注意
print(np_zeros, np_zeros.dtype)
print(np_ones, np_ones.dtype)
print(np_eye, np_eye.dtype)
print(np_random, np_random.dtype)

[[0. 0. 0.]
 [0. 0. 0.]] float64
[[1. 1. 1.]
 [1. 1. 1.]] float64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] float64
[[0.24085669 0.0794469  0.79100958]
 [0.93216654 0.4858942  0.60557645]] float64


In [11]:
# Tensorのshapeを表示
zeros_tensor.shape

torch.Size([2, 3])

### Tensorの操作

In [12]:
# サンプルのTensorとNumpy Arrayを作成
tensor_example = torch.rand((2, 3, 4))
np_example = np.random.rand(2, 3, 4)
print(tensor_example, np_example)

tensor([[[0.2566, 0.7936, 0.9408, 0.1332],
         [0.9346, 0.5936, 0.8694, 0.5677],
         [0.7411, 0.4294, 0.8854, 0.5739]],

        [[0.2666, 0.6274, 0.2696, 0.4414],
         [0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062]]]) [[[0.96320061 0.29667264 0.55869546 0.90830344]
  [0.85471293 0.90077511 0.64138294 0.16808875]
  [0.99938275 0.12047033 0.35890465 0.47553223]]

 [[0.15832426 0.33934903 0.19910761 0.50171379]
  [0.06330832 0.1433997  0.13685701 0.38169832]
  [0.95003842 0.20035515 0.16449229 0.32894554]]]


In [13]:
# 転置
permuted_tensor = torch.permute(tensor_example, (1, 0, 2))
transposed_np = np.transpose(np_example, (1, 0, 2))
print("Original shape of tensor:", tensor_example.shape)
print("Permuted tensor:", permuted_tensor.shape)
print("Transposed numpy array:", transposed_np.shape)

# torch.transpose()は，二つの軸を入れ替えるだけ
transposed_tensor = torch.transpose(tensor_example, 0, 1)
print("Original shape of tensor:", tensor_example.shape)
print("Transposed tensor:", transposed_tensor.shape)

Original shape of tensor: torch.Size([2, 3, 4])
Permuted tensor: torch.Size([3, 2, 4])
Transposed numpy array: (3, 2, 4)
Original shape of tensor: torch.Size([2, 3, 4])
Transposed tensor: torch.Size([3, 2, 4])


In [14]:
# reshape
reshaped_tensor = torch.reshape(tensor_example, (6, 4))
reshaped_np = np.reshape(np_example, (6, 4))

# 結果を表示
print("Original shape of tensor:", tensor_example.shape)
print("Reshaped tensor:", reshaped_tensor.shape)
print("Reshaped numpy array:", reshaped_np.shape)

Original shape of tensor: torch.Size([2, 3, 4])
Reshaped tensor: torch.Size([6, 4])
Reshaped numpy array: (6, 4)


In [15]:
# 基本的には元のメモリをそのまま使っている
# reshape後のtensorを変更すると，元のtensorも変更されている
print(tensor_example[0])
reshaped_tensor[0] = 0
print(tensor_example[0])

tensor([[0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739]])
tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739]])


In [16]:
# メモリが連続でなければreshape後のtensorはコピーを返す
# 連続的なメモリレイアウトを持つTensorを作成
x = torch.tensor([[1, 2], [3, 4], [5, 6]])

# 連続的なメモリレイアウトを持たない部分Tensorを取得 (transposed tensor)
y = x.T

# y は非連続的なメモリレイアウトを持つことを確認
print(y.is_contiguous())  # False が出力される

# reshape を使用して y の形状を変更
z = y.reshape(-1)
# 以下はエラーになる
# z = y.view(-1)

# z が y とメモリを共有していないことを確認 (コピーが作成されたことを意味する)
print(z.data_ptr() == y.data_ptr())  # False が出力される

False
False


In [17]:
# flatten
flattened_tensor = torch.flatten(tensor_example)
flattened_np = np_example.flatten()
print("Flattened tensor:", flattened_tensor.shape)
print("Flattened numpy array:", flattened_np.shape)

Flattened tensor: torch.Size([24])
Flattened numpy array: (24,)


In [18]:
# squeeze（サイズが1の次元を削除）
tensor_example = torch.tensor([[[1], [2], [3]]])
np_example = np.array([[[1], [2], [3]]])
print(tensor_example.shape)
print(np_example.shape)

torch.Size([1, 3, 1])
(1, 3, 1)


In [19]:
squeezed_tensor = torch.squeeze(tensor_example) # 形状が(3,)になる
squeezed_np = np.squeeze(np_example)   # 形状が(3,)になる
print("Squeezed tensor:", squeezed_tensor.shape)
print("Squeezed numpy array:", squeezed_np.shape)

Squeezed tensor: torch.Size([3])
Squeezed numpy array: (3,)


In [20]:
# unsqueeze（指定した位置に新しい次元を追加）
unsqueeze_tensor = torch.unsqueeze(tensor_example, 0) # 0次元目に新しい次元を追加
expand_dims_np = np.expand_dims(np_example, 0) # 0次元目に新しい次元を追加
print("Unsqueezed tensor:", unsqueeze_tensor.shape)
print("Unsqueezed numpy array:", expand_dims_np.shape)

Unsqueezed tensor: torch.Size([1, 1, 3, 1])
Unsqueezed numpy array: (1, 1, 3, 1)


In [21]:
# unsqueezeと同様の操作
tensor_example[None, :, :, :].shape

torch.Size([1, 1, 3, 1])

### Tensorの便利関数

In [22]:
# サンプルのTensorとNumpy Array作成
tensor_example = torch.rand((2, 3))
np_example = np.random.rand(2, 3)
print(tensor_example)
print(np_example)

tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])
[[0.65065284 0.65310825 0.77100737]
 [0.67840555 0.81108503 0.05991867]]


In [23]:
# 合計
sum_tensor = torch.sum(tensor_example)
sum_np = np.sum(np_example)

# 平均
mean_tensor = torch.mean(tensor_example)
mean_np = np.mean(np_example)

# 標準偏差
std_tensor = torch.std(tensor_example)
std_np = np.std(np_example)

# 平方根
sqrt_tensor = torch.sqrt(tensor_example)
sqrt_np = np.sqrt(np_example)

# 結果を表示
print("Sum of tensor:", sum_tensor)
print("Sum of numpy array:", sum_np)
print("Mean of tensor:", mean_tensor)
print("Mean of numpy array:", mean_np)
print("Standard deviation of tensor:", std_tensor)
print("Standard deviation of numpy array:", std_np)
print("Square root of tensor:", sqrt_tensor)
print("Square root of numpy array:", sqrt_np)

Sum of tensor: tensor(3.6427)
Sum of numpy array: 3.6241777105827175
Mean of tensor: tensor(0.6071)
Mean of numpy array: 0.6040296184304529
Standard deviation of tensor: tensor(0.3444)
Standard deviation of numpy array: 0.25064066143283414
Square root of tensor: tensor([[0.9755, 0.2743, 0.9413],
        [0.7637, 0.5811, 0.8994]])
Square root of numpy array: [[0.80663055 0.80815113 0.87807025]
 [0.82365378 0.90060259 0.24478291]]


### 行列の演算

#### 加減算+要素毎の乗除算

In [24]:
# 3x3のTensorを作成
a = torch.rand((3, 3))
b = torch.rand((3, 3))
print(a)
print(b)

tensor([[0.5779, 0.9040, 0.5547],
        [0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890]])
tensor([[0.2814, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050],
        [0.3068, 0.1165, 0.9103]])


In [25]:
# 加減算および要素毎の剰余算
add = a + b
sub = a - b
mul = a * b
div = a / b

In [26]:
# 行列の積
mm = torch.mm(a, b)
matmul = torch.matmul(a, b)
at_op = a @ b
print(mm)
print(matmul)
print(at_op)

tensor([[1.0143, 0.6969, 0.8501],
        [0.6864, 0.4363, 0.5367],
        [1.1555, 0.8370, 1.1418]])
tensor([[1.0143, 0.6969, 0.8501],
        [0.6864, 0.4363, 0.5367],
        [1.1555, 0.8370, 1.1418]])
tensor([[1.0143, 0.6969, 0.8501],
        [0.6864, 0.4363, 0.5367],
        [1.1555, 0.8370, 1.1418]])


### ブロードキャスティング

In [27]:
# (3, 3)とスカラーの演算
a = torch.rand((3, 3))
scalar = 5
result1 = a + scalar
print(a)
print(result1)

tensor([[0.6440, 0.7071, 0.6581],
        [0.4913, 0.8913, 0.1447],
        [0.5315, 0.1587, 0.6542]])
tensor([[5.6440, 5.7071, 5.6581],
        [5.4913, 5.8913, 5.1447],
        [5.5315, 5.1587, 5.6542]])


In [28]:
# (3, 3)と(1, 3)の演算
b = torch.rand((1, 3))
result2 = a + b
print(a)
print(b)
print(result2)

tensor([[0.6440, 0.7071, 0.6581],
        [0.4913, 0.8913, 0.1447],
        [0.5315, 0.1587, 0.6542]])
tensor([[0.3278, 0.6532, 0.3958]])
tensor([[0.9718, 1.3603, 1.0540],
        [0.8191, 1.5445, 0.5406],
        [0.8593, 0.8119, 1.0500]])


In [29]:
# (32, 128, 128, 3)と(128, 128, 3)の演算
c = torch.rand((32, 128, 128, 3))
d = torch.rand((128, 128, 3))
result3 = c + d
print(result3.shape)

torch.Size([32, 128, 128, 3])


In [30]:
# (32, 128, 128, 3)と(128, 128, 6)の演算は形状が不一致なためエラー
c = torch.rand((32, 128, 128, 3))
d = torch.rand((128, 128, 6))
# 以下はエラー
# result3 = c + d 
# print(result3.shape)

In [31]:
# (1, 128, 128, 3)と(8, 128, 128, 1)の演算
e = torch.rand((1, 128, 128, 3))
f = torch.rand((8, 128, 128, 1))
result4 = e + f
print(result4.shape)

torch.Size([8, 128, 128, 3])
